export default {
    AUTH_TOKEN: 'AUTH_TOKEN',
    USER_ID: 'USER_ID',
    HAS_SESSION: 'HAS_SESSION',
    CURRENT_USER: 'CURRENT_USER',
    AUTHENTICATED: 'AUTHENTICATED',
    CLIENT_ID: 'CLIENT_ID',
    LAST_QUESTION_ID: 'LAST_QUESTION_ID'
}